version: '3'
services:
  app:
    container_name: sshmon_main
    restart: always
    image: sshmon:surreal
    ports:
      - "8080:8080"
    networks:
      - network
  surrealdb:
    container_name: sshmon_surrealdb
    restart: always
    image: surrealdb/surrealdb:latest
    command: start --user root --pass root memory
    ports:
      - "8000:8000"
    networks:
      - network
volumes:
  volume: {}
networks:
  network: